"""Table sets: the uniquely-named tables one integration test owns.

Oracle can bind values as parameters but never identifiers, so a table name that is only known at
runtime has to be interpolated into the SQL string. Every interpolation in this project draws its
names from a ``TableSet``, whose suffixes are generated rather than user-supplied. See
docs/adr/0001-per-test-table-sets-for-isolation.md.
"""

from dataclasses import dataclass
from uuid import uuid4


@dataclass(frozen=True)
class TableSet:
    """The pair of tables belonging to a single test, dropped when that test finishes."""

    customers: str
    orders: str

    @classmethod
    def generate(cls) -> "TableSet":
        """Name a fresh table set, distinct from every other in the database."""
        suffix = uuid4().hex[:8]
        return cls(customers=f"customers_{suffix}", orders=f"orders_{suffix}")


def create(connection, tables: TableSet) -> None:
    """Create the table set. DDL commits implicitly in Oracle, so this is durable at once."""
    with connection.cursor() as cursor:
        cursor.execute(f"""
            CREATE TABLE {tables.customers} (
                id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name  VARCHAR2(50) NOT NULL,
                email VARCHAR2(100)
            )
        """)
        cursor.execute(f"""
            CREATE TABLE {tables.orders} (
                id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id NUMBER NOT NULL
                            REFERENCES {tables.customers} (id),
                amount      NUMBER(10, 2) NOT NULL,
                placed_at   TIMESTAMP NOT NULL
            )
        """)


def drop(connection, tables: TableSet) -> None:
    """Drop the table set. Orders first: it holds the foreign key."""
    with connection.cursor() as cursor:
        for table in (tables.orders, tables.customers):
            cursor.execute(f"DROP TABLE {table} PURGE")
